### ISSUE TITLE
Change the section id and the nav links url

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/NEW-YOSHITHA-WEBSITE#158]
https://github.com/YoshithaRathnayake/NEW-YOSHITHA-WEBSITE/blob/55d51650175b7d4608a8f3a70a685d980b1d47dc/dark/index.html#L72
- Change the url of this to #home
````html
<a href="#home" class="nav-items" id="home" onclick="home()">home</a>
````
#
https://github.com/YoshithaRathnayake/NEW-YOSHITHA-WEBSITE/blob/55d51650175b7d4608a8f3a70a685d980b1d47dc/dark/index.html#L102
- Change the id of this to home
````html
<section id="home">
````
# 
https://github.com/YoshithaRathnayake/NEW-YOSHITHA-WEBSITE/blob/55d51650175b7d4608a8f3a70a685d980b1d47dc/dark/assets/css/styles.css#L981
- Change these css IDs to the new id in html file
````css
#about h1 {
  text-align: center;
  position: relative;
  top: 50px;
  font-size: 90px;
  filter: blur(5px);
  font-family: impact;
  z-index: -1;
}
````

Like that change all of them in the home, about and contact
